version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: prod.dockerfile
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    # ports:
    #   - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: supersecure
      MYSQL_DATABASE: wcs
    volumes:
      - superdb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  superdb: